[package]
name = "stimmt"
version = "0.0.0"
edition = "2021"

[dependencies]
reqwest = "0.12.7"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["rt", "macros"] }
